# Generated by Django 4.2.3 on 2023-08-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
